sudo: true
language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=chromium-browser
  - npm prune
  - "npm i -g npm@^3"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_failure:
  - cat /home/travis/build/fulls1z3/ng2-metadata/npm-debug.log
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always